import {
  Archive,
  ArrowLeft,
  AtSign,
  AudioLines,
  Ban,
  Bell,
  BellOff,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleHelp,
  Copy,
  Download,
  Eye,
  EyeOff,
  FileText,
  Fingerprint,
  Forward,
  Gauge,
  Hourglass,
  HelpCircle,
  ImageOff,
  Images,
  KeyRound,
  Languages,
  Laptop,
  LockKeyhole,
  LogIn,
  LogOut,
  Megaphone,
  MessageCircle,
  MessagesSquare,
  Mic,
  MicOff,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Paperclip,
  Pause,
  Pencil,
  Phone,
  PhoneOff,
  Pin,
  Play,
  RefreshCwOff,
  Reply,
  ScreenShare,
  Search,
  SearchX,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  ShieldPlus,
  Smile,
  SmilePlus,
  Square,
  SquarePen,
  Star,
  Sun,
  Trash2,
  UserCircle,
  UserMinus,
  UserPlus,
  UserRound,
  UserRoundPlus,
  UsersRound,
  Video,
  VideoOff,
  Volume2,
  WifiOff,
  X,
} from 'lucide-react';

const iconMap = {
  account_circle: UserCircle,
  add_moderator: ShieldPlus,
  admin: ShieldCheck,
  add_reaction: SmilePlus,
  admin_panel_settings: ShieldCheck,
  alternate_email: AtSign,
  archive: Archive,
  arrow_back: ArrowLeft,
  attach_file: Paperclip,
  block: Ban,
  call: Phone,
  call_end: PhoneOff,
  chat_bubble: MessageCircle,
  check: Check,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  content_copy: Copy,
  delete: Trash2,
  download: Download,
  edit: Pencil,
  edit_square: SquarePen,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  fingerprint: Fingerprint,
  forum: MessagesSquare,
  forward: Forward,
  graphic_eq: AudioLines,
  groups: UsersRound,
  group_add: UsersRound,
  hourglass_empty: Hourglass,
  help: HelpCircle,
  image_not_supported: ImageOff,
  key: KeyRound,
  language: Languages,
  lock: LockKeyhole,
  login: LogIn,
  logout: LogOut,
  mic: Mic,
  mic_off: MicOff,
  mode_comment: MessageCircle,
  monitor: Monitor,
  campaign: Megaphone,
  dark_mode: Moon,
  desktop_windows: Monitor,
  more_horiz: MoreHorizontal,
  more_vert: MoreVertical,
  inventory_2: Archive,
  light_mode: Sun,
  notifications: Bell,
  notifications_off: BellOff,
  password: KeyRound,
  pause: Pause,
  person: UserRound,
  person_add: UserPlus,
  person_remove: UserMinus,
  photo_library: Images,
  play_arrow: Play,
  push_pin: Pin,
  reply: Reply,
  screen_share: ScreenShare,
  search: Search,
  search_off: SearchX,
  security: ShieldCheck,
  send: Send,
  sentiment_satisfied: Smile,
  settings: Settings,
  shield_person: Shield,
  speed: Gauge,
  star: Star,
  stop: Square,
  sync_problem: RefreshCwOff,
  theme_dark: Moon,
  theme_light: Sun,
  theme_system: Laptop,
  verified_user: ShieldCheck,
  videocam: Video,
  videocam_off: VideoOff,
  volume_up: Volume2,
  visibility: Eye,
  visibility_off: EyeOff,
  wifi_off: WifiOff,
};

function AppIcon({ name, className = '', strokeWidth = 2, ...props }) {
  const normalizedName = typeof name === 'string' ? name : String(name || '');
  const Icon = iconMap[normalizedName] || CircleHelp;

  return (
    <Icon
      aria-hidden="true"
      focusable="false"
      strokeWidth={strokeWidth}
      className={`inline-block h-[1em] w-[1em] shrink-0 ${className}`}
      {...props}
    />
  );
}

export default AppIcon;
